## Import the data and explore and clean thedata set

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('C:/coursera/ibm data science/capstone/Data-Collisions.csv', index_col = 0)

df.shape

C:\Users\andyclark\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


(194673, 37)

In [3]:
df.columns

Index(['X', 'Y', 'OBJECTID', 'INCKEY', 'COLDETKEY', 'REPORTNO', 'STATUS',
       'ADDRTYPE', 'INTKEY', 'LOCATION', 'EXCEPTRSNCODE', 'EXCEPTRSNDESC',
       'SEVERITYCODE.1', 'SEVERITYDESC', 'COLLISIONTYPE', 'PERSONCOUNT',
       'PEDCOUNT', 'PEDCYLCOUNT', 'VEHCOUNT', 'INCDATE', 'INCDTTM',
       'JUNCTIONTYPE', 'SDOT_COLCODE', 'SDOT_COLDESC', 'INATTENTIONIND',
       'UNDERINFL', 'WEATHER', 'ROADCOND', 'LIGHTCOND', 'PEDROWNOTGRNT',
       'SDOTCOLNUM', 'SPEEDING', 'ST_COLCODE', 'ST_COLDESC', 'SEGLANEKEY',
       'CROSSWALKKEY', 'HITPARKEDCAR'],
      dtype='object')

# Create a copy of original data set then remove unnecessary columns

In [4]:
df1 = df.copy()
df1.drop(['OBJECTID','INCKEY','COLDETKEY','REPORTNO','STATUS','ADDRTYPE','INTKEY','LOCATION','EXCEPTRSNCODE',\
'EXCEPTRSNDESC', 'SEVERITYDESC','SDOTCOLNUM','ST_COLCODE','ST_COLDESC','SEGLANEKEY','CROSSWALKKEY','HITPARKEDCAR'], axis=1, inplace=True)

df1.drop(['INCDATE'], axis=1, inplace=True)

# Some columns with blank data filled in with appropriate information, ie speeding under the influence to complete the data set

In [5]:
df1.loc[df1['SPEEDING'] != 'Y', 'SPEEDING'] = 'N' 
df1.loc[df1['INATTENTIONIND'] != 'Y', 'INATTENTIONIND'] = 'N' 
df1.loc[df1['UNDERINFL'] != 'Y', 'UNDERINFL'] = 'N' 
df1.loc[df1['PEDROWNOTGRNT'] != 'Y', 'PEDROWNOTGRNT'] = 'N' 
df1.columns


Index(['X', 'Y', 'SEVERITYCODE.1', 'COLLISIONTYPE', 'PERSONCOUNT', 'PEDCOUNT',
       'PEDCYLCOUNT', 'VEHCOUNT', 'INCDTTM', 'JUNCTIONTYPE', 'SDOT_COLCODE',
       'SDOT_COLDESC', 'INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND',
       'LIGHTCOND', 'PEDROWNOTGRNT', 'SPEEDING'],
      dtype='object')

In [6]:
df1['PEDROWNOTGRNT'].value_counts()

N    190006
Y      4667
Name: PEDROWNOTGRNT, dtype: int64

In [7]:
df1.dropna(how='any', inplace=True)
df1.shape

(180067, 19)

# Split the date time and keep only rows with complete data time data

In [8]:
df1[['DATE','TIME']] = df1.INCDTTM.str.split(" ", expand=True)
df1.columns


Index(['X', 'Y', 'SEVERITYCODE.1', 'COLLISIONTYPE', 'PERSONCOUNT', 'PEDCOUNT',
       'PEDCYLCOUNT', 'VEHCOUNT', 'INCDTTM', 'JUNCTIONTYPE', 'SDOT_COLCODE',
       'SDOT_COLDESC', 'INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND',
       'LIGHTCOND', 'PEDROWNOTGRNT', 'SPEEDING', 'DATE', 'TIME'],
      dtype='object')

In [9]:
df1.dropna(how='any', inplace=True)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 155403 entries, 2 to 1
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   X               155403 non-null  float64
 1   Y               155403 non-null  float64
 2   SEVERITYCODE.1  155403 non-null  int64  
 3   COLLISIONTYPE   155403 non-null  object 
 4   PERSONCOUNT     155403 non-null  int64  
 5   PEDCOUNT        155403 non-null  int64  
 6   PEDCYLCOUNT     155403 non-null  int64  
 7   VEHCOUNT        155403 non-null  int64  
 8   INCDTTM         155403 non-null  object 
 9   JUNCTIONTYPE    155403 non-null  object 
 10  SDOT_COLCODE    155403 non-null  int64  
 11  SDOT_COLDESC    155403 non-null  object 
 12  INATTENTIONIND  155403 non-null  object 
 13  UNDERINFL       155403 non-null  object 
 14  WEATHER         155403 non-null  object 
 15  ROADCOND        155403 non-null  object 
 16  LIGHTCOND       155403 non-null  object 
 17  PEDROWNOTGRNT  

# Compare the cleaned data set to the original
# 25% less rows but still around 30% of the accidents are injuries

In [10]:
df1.shape
df1['SEVERITYCODE.1'].value_counts()

1    106764
2     48639
Name: SEVERITYCODE.1, dtype: int64

In [11]:
df['SEVERITYCODE.1'].value_counts()

1    136485
2     58188
Name: SEVERITYCODE.1, dtype: int64

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 155403 entries, 2 to 1
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   X               155403 non-null  float64
 1   Y               155403 non-null  float64
 2   SEVERITYCODE.1  155403 non-null  int64  
 3   COLLISIONTYPE   155403 non-null  object 
 4   PERSONCOUNT     155403 non-null  int64  
 5   PEDCOUNT        155403 non-null  int64  
 6   PEDCYLCOUNT     155403 non-null  int64  
 7   VEHCOUNT        155403 non-null  int64  
 8   INCDTTM         155403 non-null  object 
 9   JUNCTIONTYPE    155403 non-null  object 
 10  SDOT_COLCODE    155403 non-null  int64  
 11  SDOT_COLDESC    155403 non-null  object 
 12  INATTENTIONIND  155403 non-null  object 
 13  UNDERINFL       155403 non-null  object 
 14  WEATHER         155403 non-null  object 
 15  ROADCOND        155403 non-null  object 
 16  LIGHTCOND       155403 non-null  object 
 17  PEDROWNOTGRNT  

In [13]:
df1['DATE_TIME'] = df1['DATE'] + " " + df1['TIME']
df1['DATE_TIME'] = pd.to_datetime(df1['DATE_TIME'], format="%m/%d/%Y %H:%M")
df1.drop(['INCDTTM'], axis = 1, inplace=True)
df1.drop(['DATE', 'TIME'], axis = 1, inplace=True)

df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 155403 entries, 2 to 1
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype         
---  ------          --------------   -----         
 0   X               155403 non-null  float64       
 1   Y               155403 non-null  float64       
 2   SEVERITYCODE.1  155403 non-null  int64         
 3   COLLISIONTYPE   155403 non-null  object        
 4   PERSONCOUNT     155403 non-null  int64         
 5   PEDCOUNT        155403 non-null  int64         
 6   PEDCYLCOUNT     155403 non-null  int64         
 7   VEHCOUNT        155403 non-null  int64         
 8   JUNCTIONTYPE    155403 non-null  object        
 9   SDOT_COLCODE    155403 non-null  int64         
 10  SDOT_COLDESC    155403 non-null  object        
 11  INATTENTIONIND  155403 non-null  object        
 12  UNDERINFL       155403 non-null  object        
 13  WEATHER         155403 non-null  object        
 14  ROADCOND        155403 non-null  object  

## Add month, day and hour categories

In [14]:
df1['HOUR'] = df1['DATE_TIME'].dt.hour
df1['DAY'] = df1['DATE_TIME'].dt.day
df1['MONTH'] = df1['DATE_TIME'].dt.month
df1.head()

X          Y  SEVERITYCODE.1 COLLISIONTYPE  \
SEVERITYCODE                                                        
2            -122.323148  47.703140               2        Angles   
1            -122.347294  47.647172               1     Sideswipe   
1            -122.334540  47.607871               1    Parked Car   
1            -122.334803  47.604803               1         Other   
2            -122.306426  47.545739               2        Angles   

              PERSONCOUNT  PEDCOUNT  PEDCYLCOUNT  VEHCOUNT  \
SEVERITYCODE                                                 
2                       2         0            0         2   
1                       2         0            0         2   
1                       4         0            0         3   
1                       3         0            0         3   
2                       2         0            0         2   

                                         JUNCTIONTYPE  SDOT_COLCODE  ...  \
SEVERITYCODE                                                         ...   
2              At Intersection (intersection related)            11  ...   
1             Mid-Block (not related to intersection)            16  ...   
1             Mid-Block (not related to intersection)            14  ...   
1             Mid-Block (not related to intersection)            11  ...   
2              At Intersection (intersection related)            11  ...   

             UNDERINFL   WEATHER ROADCOND                LIGHTCOND  \
SEVERITYCODE                                                         
2                    N  Overcast      Wet                 Daylight   
1                    N   Raining      Wet  Dark - Street Lights On   
1                    N  Overcast      Dry                 Daylight   
1                    N     Clear      Dry                 Daylight   
2                    N   Raining      Wet                 Daylight   

             PEDROWNOTGRNT SPEEDING           DATE_TIME HOUR DAY  MONTH  
SEVERITYCODE                                                             
2                        N        N 2013-03-27 14:54:00   14  27      3  
1                        N        N 2006-12-20 18:55:00   18  20     12  
1                        N        N 2004-11-18 10:20:00   10  18     11  
1                        N        N 2013-03-29 09:26:00    9  29      3  
2                        N        N 2004-01-28 08:04:00    8  28      1  

[5 rows x 22 columns]

## Create a balanced data set by downsampling the majority class Damage

In [15]:
df_dam = df1[df1['SEVERITYCODE.1'] == 1]
print(df_dam.shape)
df_inj = df1[df1['SEVERITYCODE.1'] == 2]
print(df_inj.shape)

(106764, 22)
(48639, 22)


# Down sampled majority

In [16]:
from sklearn.utils import resample

df_dam_downsampled = resample(df_dam, 
                             replace=False,     # sample without replacement
                             n_samples=48639,   # cases to match minority case
                             random_state=15)   # reproducible results

print(f"The number of rows in the downsampled set of damage collisions are: {df_dam_downsampled.shape[0]}.")
print(f"The number of rows in the injury collisions are: {df_inj.shape[0]}.")
print("The data frames are now balanced.")
df_bal = pd.concat([df_dam_downsampled, df_inj])
df_bal.shape

The number of rows in the downsampled set of damage collisions are: 48639.
The number of rows in the injury collisions are: 48639.
The data frames are now balanced.


(97278, 22)

## Remove additional columns, focus on the environmental variables

In [17]:
df_bal.drop(['SDOT_COLDESC'], axis=1, inplace=True)
df_bal.columns

Index(['X', 'Y', 'SEVERITYCODE.1', 'COLLISIONTYPE', 'PERSONCOUNT', 'PEDCOUNT',
       'PEDCYLCOUNT', 'VEHCOUNT', 'JUNCTIONTYPE', 'SDOT_COLCODE',
       'INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND', 'LIGHTCOND',
       'PEDROWNOTGRNT', 'SPEEDING', 'DATE_TIME', 'HOUR', 'DAY', 'MONTH'],
      dtype='object')

In [18]:
df_bal.drop(['X','Y'], axis=1, inplace=True)
df_bal.columns

Index(['SEVERITYCODE.1', 'COLLISIONTYPE', 'PERSONCOUNT', 'PEDCOUNT',
       'PEDCYLCOUNT', 'VEHCOUNT', 'JUNCTIONTYPE', 'SDOT_COLCODE',
       'INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND', 'LIGHTCOND',
       'PEDROWNOTGRNT', 'SPEEDING', 'DATE_TIME', 'HOUR', 'DAY', 'MONTH'],
      dtype='object')

In [19]:
df_bal.drop(['DATE_TIME'], axis=1, inplace=True)
df_bal.columns

Index(['SEVERITYCODE.1', 'COLLISIONTYPE', 'PERSONCOUNT', 'PEDCOUNT',
       'PEDCYLCOUNT', 'VEHCOUNT', 'JUNCTIONTYPE', 'SDOT_COLCODE',
       'INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND', 'LIGHTCOND',
       'PEDROWNOTGRNT', 'SPEEDING', 'HOUR', 'DAY', 'MONTH'],
      dtype='object')

In [20]:
df_bal.drop(['PERSONCOUNT','VEHCOUNT'], axis=1, inplace=True)
df_bal.columns

Index(['SEVERITYCODE.1', 'COLLISIONTYPE', 'PEDCOUNT', 'PEDCYLCOUNT',
       'JUNCTIONTYPE', 'SDOT_COLCODE', 'INATTENTIONIND', 'UNDERINFL',
       'WEATHER', 'ROADCOND', 'LIGHTCOND', 'PEDROWNOTGRNT', 'SPEEDING', 'HOUR',
       'DAY', 'MONTH'],
      dtype='object')

In [21]:
df_bal.drop(['COLLISIONTYPE'], axis=1, inplace=True)
df_bal.columns

Index(['SEVERITYCODE.1', 'PEDCOUNT', 'PEDCYLCOUNT', 'JUNCTIONTYPE',
       'SDOT_COLCODE', 'INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND',
       'LIGHTCOND', 'PEDROWNOTGRNT', 'SPEEDING', 'HOUR', 'DAY', 'MONTH'],
      dtype='object')

In [22]:
df_bal.columns

Index(['SEVERITYCODE.1', 'PEDCOUNT', 'PEDCYLCOUNT', 'JUNCTIONTYPE',
       'SDOT_COLCODE', 'INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND',
       'LIGHTCOND', 'PEDROWNOTGRNT', 'SPEEDING', 'HOUR', 'DAY', 'MONTH'],
      dtype='object')

##  Set up the X as the feature matrix and Y as the response vector

In [23]:
X = df_bal[['INATTENTIONIND','UNDERINFL','WEATHER','SPEEDING','HOUR','DAY','MONTH','PEDCOUNT',\
           'PEDCYLCOUNT','JUNCTIONTYPE','SDOT_COLCODE','ROADCOND','LIGHTCOND','PEDROWNOTGRNT']].values
X[0:5]

array([['N', 'N', 'Clear', 'N', 23, 7, 5, 0, 0,
        'Mid-Block (not related to intersection)', 11, 'Dry',
        'Dark - Street Lights On', 'N'],
       ['N', 'N', 'Unknown', 'N', 18, 27, 3, 0, 0,
        'Mid-Block (not related to intersection)', 16, 'Unknown',
        'Unknown', 'N'],
       ['N', 'N', 'Overcast', 'N', 17, 17, 6, 0, 0,
        'At Intersection (intersection related)', 11, 'Dry', 'Daylight',
        'N'],
       ['Y', 'N', 'Clear', 'N', 5, 30, 6, 0, 0,
        'Mid-Block (not related to intersection)', 0, 'Dry', 'Daylight',
        'N'],
       ['N', 'N', 'Unknown', 'N', 12, 21, 8, 0, 0,
        'Mid-Block (not related to intersection)', 0, 'Unknown',
        'Unknown', 'N']], dtype=object)

In [24]:
X_df = df_bal[['INATTENTIONIND','UNDERINFL','WEATHER','SPEEDING','HOUR','DAY','MONTH',\
              'PEDCOUNT','PEDCYLCOUNT','JUNCTIONTYPE','SDOT_COLCODE','ROADCOND','LIGHTCOND','PEDROWNOTGRNT']]
X_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 97278 entries, 1 to 2
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   INATTENTIONIND  97278 non-null  object
 1   UNDERINFL       97278 non-null  object
 2   WEATHER         97278 non-null  object
 3   SPEEDING        97278 non-null  object
 4   HOUR            97278 non-null  int64 
 5   DAY             97278 non-null  int64 
 6   MONTH           97278 non-null  int64 
 7   PEDCOUNT        97278 non-null  int64 
 8   PEDCYLCOUNT     97278 non-null  int64 
 9   JUNCTIONTYPE    97278 non-null  object
 10  SDOT_COLCODE    97278 non-null  int64 
 11  ROADCOND        97278 non-null  object
 12  LIGHTCOND       97278 non-null  object
 13  PEDROWNOTGRNT   97278 non-null  object
dtypes: int64(6), object(8)
memory usage: 11.1+ MB


In [25]:
from sklearn import preprocessing

le_inattentionind = preprocessing.LabelEncoder()
le_inattentionind.fit(['N','Y'])
X[:,0] = le_inattentionind.transform(X[:,0])
X[0:5]

array([[0, 'N', 'Clear', 'N', 23, 7, 5, 0, 0,
        'Mid-Block (not related to intersection)', 11, 'Dry',
        'Dark - Street Lights On', 'N'],
       [0, 'N', 'Unknown', 'N', 18, 27, 3, 0, 0,
        'Mid-Block (not related to intersection)', 16, 'Unknown',
        'Unknown', 'N'],
       [0, 'N', 'Overcast', 'N', 17, 17, 6, 0, 0,
        'At Intersection (intersection related)', 11, 'Dry', 'Daylight',
        'N'],
       [1, 'N', 'Clear', 'N', 5, 30, 6, 0, 0,
        'Mid-Block (not related to intersection)', 0, 'Dry', 'Daylight',
        'N'],
       [0, 'N', 'Unknown', 'N', 12, 21, 8, 0, 0,
        'Mid-Block (not related to intersection)', 0, 'Unknown',
        'Unknown', 'N']], dtype=object)

In [26]:
le_underinfl = preprocessing.LabelEncoder()
le_underinfl.fit(['N','Y'])
X[:,1] = le_underinfl.transform(X[:,1])
X[0:5]

array([[0, 0, 'Clear', 'N', 23, 7, 5, 0, 0,
        'Mid-Block (not related to intersection)', 11, 'Dry',
        'Dark - Street Lights On', 'N'],
       [0, 0, 'Unknown', 'N', 18, 27, 3, 0, 0,
        'Mid-Block (not related to intersection)', 16, 'Unknown',
        'Unknown', 'N'],
       [0, 0, 'Overcast', 'N', 17, 17, 6, 0, 0,
        'At Intersection (intersection related)', 11, 'Dry', 'Daylight',
        'N'],
       [1, 0, 'Clear', 'N', 5, 30, 6, 0, 0,
        'Mid-Block (not related to intersection)', 0, 'Dry', 'Daylight',
        'N'],
       [0, 0, 'Unknown', 'N', 12, 21, 8, 0, 0,
        'Mid-Block (not related to intersection)', 0, 'Unknown',
        'Unknown', 'N']], dtype=object)

In [27]:
X_df['SPEEDING'].value_counts()

N    92387
Y     4891
Name: SPEEDING, dtype: int64

In [28]:
le_weather = preprocessing.LabelEncoder()
le_weather.fit(['Clear','Raining','Overcast','Unknown','Snowing','Other','Fog/Smog/Smoke','Sleet/Hail/Freezing Rain',\
               'Blowing Sand/Dirt','Severe Crosswind','Partly Cloudy'])
X[:,2] = le_weather.transform(X[:,2])
X[0:5]

array([[0, 0, 1, 'N', 23, 7, 5, 0, 0,
        'Mid-Block (not related to intersection)', 11, 'Dry',
        'Dark - Street Lights On', 'N'],
       [0, 0, 10, 'N', 18, 27, 3, 0, 0,
        'Mid-Block (not related to intersection)', 16, 'Unknown',
        'Unknown', 'N'],
       [0, 0, 4, 'N', 17, 17, 6, 0, 0,
        'At Intersection (intersection related)', 11, 'Dry', 'Daylight',
        'N'],
       [1, 0, 1, 'N', 5, 30, 6, 0, 0,
        'Mid-Block (not related to intersection)', 0, 'Dry', 'Daylight',
        'N'],
       [0, 0, 10, 'N', 12, 21, 8, 0, 0,
        'Mid-Block (not related to intersection)', 0, 'Unknown',
        'Unknown', 'N']], dtype=object)

In [29]:
le_speeding = preprocessing.LabelEncoder()
le_speeding.fit(['N','Y'])
X[:,3] = le_speeding.transform(X[:,3])
X[0:5]

array([[0, 0, 1, 0, 23, 7, 5, 0, 0,
        'Mid-Block (not related to intersection)', 11, 'Dry',
        'Dark - Street Lights On', 'N'],
       [0, 0, 10, 0, 18, 27, 3, 0, 0,
        'Mid-Block (not related to intersection)', 16, 'Unknown',
        'Unknown', 'N'],
       [0, 0, 4, 0, 17, 17, 6, 0, 0,
        'At Intersection (intersection related)', 11, 'Dry', 'Daylight',
        'N'],
       [1, 0, 1, 0, 5, 30, 6, 0, 0,
        'Mid-Block (not related to intersection)', 0, 'Dry', 'Daylight',
        'N'],
       [0, 0, 10, 0, 12, 21, 8, 0, 0,
        'Mid-Block (not related to intersection)', 0, 'Unknown',
        'Unknown', 'N']], dtype=object)

In [30]:
le_junctiontype = preprocessing.LabelEncoder()
le_junctiontype.fit(['Mid-Block (not related to intersection)','At Intersection (intersection related)',\
                     'Mid-Block (but intersection related)','Driveway Junction',\
                     'At Intersection (but not related to intersection)','Ramp Junction','Unknown'])
X[:,9] = le_junctiontype.transform(X[:,9])
X[0:5]

array([[0, 0, 1, 0, 23, 7, 5, 0, 0, 4, 11, 'Dry',
        'Dark - Street Lights On', 'N'],
       [0, 0, 10, 0, 18, 27, 3, 0, 0, 4, 16, 'Unknown', 'Unknown', 'N'],
       [0, 0, 4, 0, 17, 17, 6, 0, 0, 1, 11, 'Dry', 'Daylight', 'N'],
       [1, 0, 1, 0, 5, 30, 6, 0, 0, 4, 0, 'Dry', 'Daylight', 'N'],
       [0, 0, 10, 0, 12, 21, 8, 0, 0, 4, 0, 'Unknown', 'Unknown', 'N']],
      dtype=object)

In [31]:
le_roadcond = preprocessing.LabelEncoder()
le_roadcond.fit(['Dry','Wet','Unknown','Ice','Snow/Slush','Other','Standing Water','Sand/Mud/Dirt','Oil'])
X[:,11] = le_roadcond.transform(X[:,11])
X[0:5]

array([[0, 0, 1, 0, 23, 7, 5, 0, 0, 4, 11, 0, 'Dark - Street Lights On',
        'N'],
       [0, 0, 10, 0, 18, 27, 3, 0, 0, 4, 16, 7, 'Unknown', 'N'],
       [0, 0, 4, 0, 17, 17, 6, 0, 0, 1, 11, 0, 'Daylight', 'N'],
       [1, 0, 1, 0, 5, 30, 6, 0, 0, 4, 0, 0, 'Daylight', 'N'],
       [0, 0, 10, 0, 12, 21, 8, 0, 0, 4, 0, 7, 'Unknown', 'N']],
      dtype=object)

In [32]:
le_lightcond = preprocessing.LabelEncoder()
le_lightcond.fit(['Daylight','Dark - Street Lights On','Unknown','Dusk','Dawn','Dark - No Street Lights',\
                  'Dark - Street Lights Off','Other','Dark - Unknown Lighting'])
X[:,12] = le_lightcond.transform(X[:,12])
X[0:5]

array([[0, 0, 1, 0, 23, 7, 5, 0, 0, 4, 11, 0, 2, 'N'],
       [0, 0, 10, 0, 18, 27, 3, 0, 0, 4, 16, 7, 8, 'N'],
       [0, 0, 4, 0, 17, 17, 6, 0, 0, 1, 11, 0, 5, 'N'],
       [1, 0, 1, 0, 5, 30, 6, 0, 0, 4, 0, 0, 5, 'N'],
       [0, 0, 10, 0, 12, 21, 8, 0, 0, 4, 0, 7, 8, 'N']], dtype=object)

In [33]:
le_pedrownotgrnt = preprocessing.LabelEncoder()
le_pedrownotgrnt.fit(['N','Y'])
X[:,13] = le_pedrownotgrnt.transform(X[:,13])
X[0:5]

array([[0, 0, 1, 0, 23, 7, 5, 0, 0, 4, 11, 0, 2, 0],
       [0, 0, 10, 0, 18, 27, 3, 0, 0, 4, 16, 7, 8, 0],
       [0, 0, 4, 0, 17, 17, 6, 0, 0, 1, 11, 0, 5, 0],
       [1, 0, 1, 0, 5, 30, 6, 0, 0, 4, 0, 0, 5, 0],
       [0, 0, 10, 0, 12, 21, 8, 0, 0, 4, 0, 7, 8, 0]], dtype=object)

In [34]:
X_df['PEDROWNOTGRNT'].value_counts()

N    93460
Y     3818
Name: PEDROWNOTGRNT, dtype: int64

## Fill Target Variable

In [35]:
y = df_bal['SEVERITYCODE.1']
y.head()


SEVERITYCODE
1    1
1    1
1    1
1    1
1    1
Name: SEVERITYCODE.1, dtype: int64

## Set up Decision Tree

In [36]:
from sklearn.model_selection import train_test_split

X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)

print(X_trainset.shape)
print(y_trainset.shape)

(68094, 14)
(68094,)


## Modeling the Decision Tree

In [37]:
from sklearn.tree import DecisionTreeClassifier

crashTree = DecisionTreeClassifier(criterion="entropy", max_depth = 20)
crashTree # it shows the default parameters

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=20,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [38]:
# Fit the data with the training feature X_trainset and training response y_trainset
crashTree.fit(X_trainset, y_trainset)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=20,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

## Prediction

In [39]:
predTree = crashTree.predict(X_testset)

print(predTree [0:5])
print(y_testset [0:5])

[2 1 2 1 2]
SEVERITYCODE
2    2
1    1
2    2
1    1
1    1
Name: SEVERITYCODE.1, dtype: int64


## Evaluation of Decision Tree

In [40]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, predTree))

DecisionTrees's Accuracy:  0.6391858552631579


In [58]:
print (classification_report(y_test, predTree))

              precision    recall  f1-score   support

           1       0.66      0.58      0.62     14630
           2       0.62      0.70      0.66     14554

    accuracy                           0.64     29184
   macro avg       0.64      0.64      0.64     29184
weighted avg       0.64      0.64      0.64     29184



## Logistic Regression

## First Normalize the Data Set

In [41]:
X_lr = preprocessing.StandardScaler().fit(X).transform(X)
X_lr[0:5]

array([[-0.45635212, -0.18594401, -0.70836847, -0.2300877 ,  1.74763767,
        -1.24758063, -0.45680584, -0.24375789, -0.21959625,  1.01409618,
        -0.52800394, -0.67437788, -1.44450062, -0.20211804],
       [-0.45635212, -0.18594401,  2.75670032, -0.2300877 ,  0.84628667,
         1.18135288, -1.04268863, -0.24375789, -0.21959625,  1.01409618,
         0.173671  ,  1.25989161,  2.29714517, -0.20211804],
       [-0.45635212, -0.18594401,  0.44665446, -0.2300877 ,  0.66601647,
        -0.03311388, -0.16386445, -0.24375789, -0.21959625, -1.13512491,
        -0.52800394, -0.67437788,  0.42632228, -0.20211804],
       [ 2.19129036, -0.18594401, -0.70836847, -0.2300877 , -1.49722595,
         1.5456929 , -0.16386445, -0.24375789, -0.21959625,  1.01409618,
        -2.07168881, -0.67437788,  0.42632228, -0.20211804],
       [-0.45635212, -0.18594401,  2.75670032, -0.2300877 , -0.23533454,
         0.45267283,  0.42201834, -0.24375789, -0.21959625,  1.01409618,
        -2.07168881,  1.25

## Train Test Split

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X_lr, y, test_size=0.3, random_state=3)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (68094, 14) (68094,)
Test set: (29184, 14) (29184,)


## Modeling using Logistic Regression

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

## Predict on the test set using Logistic Regression

In [44]:
yhat_lr = LR.predict(X_test)
yhat_lr

array([2, 1, 2, ..., 2, 2, 1], dtype=int64)

In [45]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.11238876, 0.88761124],
       [0.65498174, 0.34501826],
       [0.0450669 , 0.9549331 ],
       ...,
       [0.3879474 , 0.6120526 ],
       [0.13600659, 0.86399341],
       [0.53822053, 0.46177947]])

## Evaluation of Logistic Regression

In [46]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, yhat_lr)

0.4896224174780337

In [47]:
from sklearn.metrics import classification_report, confusion_matrix
print (classification_report(y_test, yhat_lr))

              precision    recall  f1-score   support

           1       0.62      0.70      0.66     14630
           2       0.65      0.56      0.60     14554

    accuracy                           0.63     29184
   macro avg       0.63      0.63      0.63     29184
weighted avg       0.63      0.63      0.63     29184



In [48]:
from sklearn.metrics import log_loss
log_loss(y_test, yhat_prob)

0.6125456822361346

## Try SVM on the prediction of injury or property damage

In [49]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
%matplotlib inline 
import matplotlib.pyplot as plt

In [50]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=3)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (68094, 14) (68094,)
Test set: (29184, 14) (29184,)


In [51]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, y_train) 

C:\Users\andyclark\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

## Evaluation of SVM  'rbf'

In [52]:
from sklearn.metrics import classification_report
import itertools

In [53]:
yhat = clf.predict(X_test)
print (classification_report(y_test, yhat))

              precision    recall  f1-score   support

           1       0.65      0.60      0.62     14630
           2       0.63      0.67      0.65     14554

    accuracy                           0.64     29184
   macro avg       0.64      0.64      0.64     29184
weighted avg       0.64      0.64      0.63     29184



In [54]:
clf2 = svm.SVC(kernel='linear')
clf2.fit(X_train, y_train) 
yhat2 = clf2.predict(X_test)
print (classification_report(y_test, yhat2))

              precision    recall  f1-score   support

           1       0.62      0.65      0.64     14630
           2       0.63      0.60      0.62     14554

    accuracy                           0.63     29184
   macro avg       0.63      0.63      0.63     29184
weighted avg       0.63      0.63      0.63     29184



In [55]:
clf3 = svm.SVC(kernel='poly', gamma = 'scale')
clf3.fit(X_train, y_train) 
yhat3 = clf3.predict(X_test)
print (classification_report(y_test, yhat3))

              precision    recall  f1-score   support

           1       0.62      0.67      0.65     14630
           2       0.64      0.59      0.62     14554

    accuracy                           0.63     29184
   macro avg       0.63      0.63      0.63     29184
weighted avg       0.63      0.63      0.63     29184



In [56]:
print('Root Mean Squared Error SVM rbf:', np.sqrt(metrics.mean_squared_error(y_test, yhat)))
print('Root Mean Squared Error SVM linear:', np.sqrt(metrics.mean_squared_error(y_test, yhat2)))
print('Root Mean Squared Error SVM poly:', np.sqrt(metrics.mean_squared_error(y_test, yhat3)))
print('Root Mean Squared Error LR:', np.sqrt(metrics.mean_squared_error(y_test, yhat_lr)))
print('Root Mean Squared Error Tree:', np.sqrt(metrics.mean_squared_error(y_test, predTree)))

Root Mean Squared Error SVM rbf: 0.6037789893516138
Root Mean Squared Error SVM linear: 0.6101582067633785
Root Mean Squared Error SVM poly: 0.6061861288474173
Root Mean Squared Error LR: 0.606807597617495
Root Mean Squared Error Tree: 0.6006780707973632
